sudo: required
dist: trusty
language: node_js
node_js:
  - '7.0.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install -g angular-cli-ghpages
- npm install

script: 
- ng test --single-run
- ng build --prod --base-href "https://joaoflf.github.io/remote-config-dashboard/" --aot=false
- angular-cli-ghpages --no-silent --repo=https://GH_TOKEN@github.com/joaoflf/remote-config-dashboard.git